# Generated by Django 4.2.7 on 2024-06-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelyear',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
