# Generated by Django 4.2.7 on 2024-06-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_modelyear_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_year',
        ),
        migrations.AddField(
            model_name='product',
            name='model_year',
            field=models.ManyToManyField(related_name='products', to='api.modelyear'),
        ),
    ]
