# Generated by Django 4.2.7 on 2024-06-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_modelyear_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_year',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='api.modelyear'),
        ),
    ]
